# Generated by Django 3.1.6 on 2021-05-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, max_length=250)),
                ('app_url', models.URLField(blank=True, max_length=250)),
                ('app_category', models.CharField(blank=True, max_length=250)),
                ('sub_category', models.CharField(blank=True, max_length=250)),
                ('app_points', models.IntegerField(blank=True)),
                ('app_pic', models.ImageField(blank=True, upload_to='app_picture')),
            ],
        ),
    ]
