# Generated by Django 3.1.6 on 2021-05-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextapp', '0005_appdetail_assigned_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetail',
            name='app_status',
            field=models.BooleanField(default=False),
        ),
    ]
