# Generated by Django 3.1.6 on 2021-05-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextapp', '0006_appdetail_app_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetail',
            name='assigned_user',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
